[workspace]
resolver = "3"
members = ["crates/ryuk", "crates/workspace"]

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false
license = "AGPL-3.0-or-later"
authors = ["Mayank Verma <errmayank@gmail.com>"]

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
workspace = { path = "crates/workspace" }
