[package]
name = "util"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[lib]
name = "util"
path = "src/util.rs"

[features]
test-support = []

[dependencies]
