[package]
name = "ryuk"
description = "Notes app."
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gpui = { workspace = true }
