[package]
name = "text"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[lib]
name = "text"
path = "src/text.rs"

[dependencies]
ropey = { workspace = true }
serde = { workspace = true }
