[package]
name = "icons"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "icons"
path = "src/icons.rs"

[dependencies]
gpui = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
