name: "Run Tests"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  check_style:
    name: "Check Style"
    if: github.repository == 'errmayank/ryuk'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10.26.2

      - name: "Check Prettier formatting"
        run: ./script/prettier
        shell: bash

      - name: "Check Rust formatting"
        run: cargo fmt --all -- --check

      - name: "Check for typos"
        uses: crate-ci/typos@v1.40.0

  run_tests_linux_x86_64:
    name: "Run tests / Linux x86_64"
    if: github.repository == 'errmayank/ryuk'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install Linux dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb-dev \
            libxkbcommon-x11-dev \
            libwayland-dev \
            libfontconfig-dev \
            libasound2-dev \
            libssl-dev

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

      - name: "Install Nextest"
        uses: taiki-e/install-action@nextest

      - name: "Run tests"
        run: cargo nextest run --workspace --no-fail-fast

  run_tests_macos_arm64:
    name: "Run tests / macOS ARM64"
    if: github.repository == 'errmayank/ryuk'
    runs-on: macos-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

      - name: "Install Nextest"
        uses: taiki-e/install-action@nextest

      - name: "Run tests"
        run: cargo nextest run --workspace --no-fail-fast

  run_tests_macos_x86_64:
    name: "Run tests / macOS x86_64"
    if: github.repository == 'errmayank/ryuk'
    runs-on: macos-15-intel
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Run Clippy"
        run: ./script/clippy
        shell: bash

      - name: "Install Nextest"
        uses: taiki-e/install-action@nextest

      - name: "Run tests"
        run: cargo nextest run --workspace --no-fail-fast

  run_tests_windows_x86_64:
    name: "Run tests / Windows x86_64"
    if: github.repository == 'errmayank/ryuk'
    runs-on: windows-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Run Clippy"
        run: ./script/clippy.ps1
        shell: pwsh

      - name: "Install Nextest"
        uses: taiki-e/install-action@nextest

      - name: "Run tests"
        run: cargo nextest run --workspace --no-fail-fast
